// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnHJsq_sPZE0Qx81p3D5OKEY8Hl4m0Z34',
    appId: '1:886197219513:web:24253500ffc1b81f5beb68',
    messagingSenderId: '886197219513',
    projectId: 'first-firebase-f3c1b',
    authDomain: 'first-firebase-f3c1b.firebaseapp.com',
    storageBucket: 'first-firebase-f3c1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCERMxcz31Tc2pUCCWJnqBFZb1lP06kiTI',
    appId: '1:886197219513:android:5b697e4ebd8acee15beb68',
    messagingSenderId: '886197219513',
    projectId: 'first-firebase-f3c1b',
    storageBucket: 'first-firebase-f3c1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjRI04bCgoWFFIGXgxC-Nftjp-ceeQtxA',
    appId: '1:886197219513:ios:1aa854afe4a8c15f5beb68',
    messagingSenderId: '886197219513',
    projectId: 'first-firebase-f3c1b',
    storageBucket: 'first-firebase-f3c1b.appspot.com',
    iosBundleId: 'com.example.toonflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjRI04bCgoWFFIGXgxC-Nftjp-ceeQtxA',
    appId: '1:886197219513:ios:4a03883c4ffab74e5beb68',
    messagingSenderId: '886197219513',
    projectId: 'first-firebase-f3c1b',
    storageBucket: 'first-firebase-f3c1b.appspot.com',
    iosBundleId: 'com.example.toonflix.RunnerTests',
  );
}
